language: bash
services: docker
before_install:
  - springestudo
  - echo "We are in the Docker Folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider:script
  script:
    docker push natanmaia17/mysql-rest-with-spring-boot-udemy;
    docker push natanmaia17/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false